#!/usr/bin/env python3
"""Generate the three secrets the app needs, and write a .env file.

Usage:
    python3 scripts/bootstrap_secrets.py                  # random passphrase
    python3 scripts/bootstrap_secrets.py --passphrase "..."  # your own

The passphrase is printed ONCE. It is stored only as a bcrypt hash. Losing it
means re-running this script; there is no reset flow, by design.
"""

import argparse
import base64
import os
import secrets
import sys

try:
    import bcrypt
except ImportError:
    sys.exit("pip install bcrypt cryptography")

try:
    from cryptography.fernet import Fernet
except ImportError:
    sys.exit("pip install bcrypt cryptography")

WORDS = (
    "anchor amber basalt cinder cobalt copper cypress delta ember falcon "
    "granite harbor indigo jasper kestrel lantern marble nimbus onyx pewter "
    "quartz ridge sable talon umber vertex willow yarrow zenith"
).split()


def make_passphrase(words=5):
    return "-".join(secrets.choice(WORDS) for _ in range(words))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--passphrase", help="use this passphrase instead of a random one")
    ap.add_argument("--out", default=".env", help="output env file (default .env)")
    ap.add_argument("--force", action="store_true", help="overwrite existing file")
    args = ap.parse_args()

    if os.path.exists(args.out) and not args.force:
        sys.exit(f"{args.out} already exists. Use --force to overwrite "
                 f"(this invalidates the current passphrase and encrypted keys).")

    passphrase = args.passphrase or make_passphrase()
    pw_hash = bcrypt.hashpw(passphrase.encode(), bcrypt.gensalt(rounds=12))
    # Base64 the hash. A raw bcrypt hash contains "$" characters, which a shell
    # expands when you `source .env` - silently corrupting the credential and
    # producing a baffling "Invalid salt" error. Base64 has no shell metachars.
    pw_hash_b64 = base64.b64encode(pw_hash).decode()

    lines = [
        "# Generated by scripts/bootstrap_secrets.py - DO NOT COMMIT",
        f"SECRET_KEY={secrets.token_urlsafe(48)}",
        f"ENCRYPTION_KEY={Fernet.generate_key().decode()}",
        f"ACCESS_PASSPHRASE_HASH_B64={pw_hash_b64}",
        "REQUIRE_HTTPS=true",
        "TRUST_PROXY=true",
        "LOG_LEVEL=INFO",
        "",
    ]
    with open(args.out, "w") as fh:
        fh.write("\n".join(lines))
    os.chmod(args.out, 0o600)

    print(f"Wrote {args.out} (mode 600).\n")
    print("=" * 58)
    print("  ACCESS PASSPHRASE - shown once, store it in a password manager")
    print("=" * 58)
    print(f"\n    {passphrase}\n")
    print("=" * 58)
    print("\nChanging ENCRYPTION_KEY later makes stored Kalshi credentials")
    print("undecryptable - you would re-enter them in the dashboard.")


if __name__ == "__main__":
    main()
